/*
 * Generated by Bluespec Compiler, version 2023.07 (build 0eb551d)
 * 
 * On Tue Apr 23 02:12:13 CST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "model_start.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_start::MODEL_start()
{
  start_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_start()
{
  MODEL_start *model = new MODEL_start();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_start &INST_top = *((MOD_start *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_has_run___d1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_do_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_do_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_finish_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_finish_start;
	 DEF_INST_top_DEF_has_run___d1 = INST_top.INST_has_run.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_do_start = !DEF_INST_top_DEF_has_run___d1;
	 DEF_INST_top_DEF_WILL_FIRE_RL_do_start = DEF_INST_top_DEF_CAN_FIRE_RL_do_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_finish_start = DEF_INST_top_DEF_has_run___d1;
	 DEF_INST_top_DEF_WILL_FIRE_RL_finish_start = DEF_INST_top_DEF_CAN_FIRE_RL_finish_start;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_do_start)
	   INST_top.RL_do_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_finish_start)
	   INST_top.RL_finish_start();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_has_run.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_start::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  start_instance = new MOD_start(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (start_instance->set_clk_0)("CLK");
}
void MODEL_start::destroy_model()
{
  delete start_instance;
  start_instance = NULL;
}
void MODEL_start::reset_model(bool asserted)
{
  (start_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_start::get_instance()
{
  return start_instance;
}

/* Fill in version numbers */
void MODEL_start::get_version(char const **name, char const **build)
{
  *name = "2023.07";
  *build = "0eb551d";
}

/* Get the model creation time */
time_t MODEL_start::get_creation_time()
{
  
  /* Mon Apr 22 18:12:13 UTC 2024 */
  return 1713809533llu;
}

/* State dumping function */
void MODEL_start::dump_state()
{
  (start_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_start & start_backing(tSimStateHdl simHdl)
{
  static MOD_start *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_start(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_start::dump_VCD_defs()
{
  (start_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_start::dump_VCD(tVCDDumpType dt)
{
  (start_instance->dump_VCD)(dt, vcd_depth(sim_hdl), start_backing(sim_hdl));
}
